package com.gdut.graduation.dao;

import com.gdut.graduation.pojo.Cart;
import org.apache.ibatis.annotations.Param;

import java.util.List;

public interface CartMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table graduation_cart
     *
     * @mbggenerated
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table graduation_cart
     *
     * @mbggenerated
     */
    int insert(Cart record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table graduation_cart
     *
     * @mbggenerated
     */
    Cart selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table graduation_cart
     *
     * @mbggenerated
     */
    List<Cart> selectAll();

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table graduation_cart
     *
     * @mbggenerated
     */
    int updateByPrimaryKey(Cart record);

    int updateQuantityByCartId(@Param("cartId") Integer cartId,@Param("quantity") Integer quantity);


    Cart selectByUserIdProductId(@Param("userId") Integer userId, @Param("productId") Integer productId);

    List<Cart> selectByUserId( Integer userId);

    List<Cart> selectCheckedCartByUserId(Integer userId);

    List<Cart> selectUnCheckedCartByUserId(Integer userId);

    int selectCartProductCount(Integer userId);

    int CheckedOrUnCheckedUpdate(@Param("userId") Integer userId, @Param("productId") Integer productId, @Param("checked") Integer checked);

    int deleteByUserIdProductIds(@Param("userId") Integer userId,@Param("productIdList") List<Integer> productIdList);

}