package com.gdut.graduation.dao;

import com.gdut.graduation.pojo.OrderItem;
import org.apache.ibatis.annotations.Param;

import java.util.List;

public interface OrderItemMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table graduation_order_item
     *
     * @mbggenerated
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table graduation_order_item
     *
     * @mbggenerated
     */
    int insert(OrderItem record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table graduation_order_item
     *
     * @mbggenerated
     */
    OrderItem selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table graduation_order_item
     *
     * @mbggenerated
     */
    List<OrderItem> selectAll();

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table graduation_order_item
     *
     * @mbggenerated
     */
    int updateByPrimaryKey(OrderItem record);

    /**
     * 批量插入orderItem
     * @param orderItemList
     * @return
     */
    int batchInsert(@Param("orderItemList") List<OrderItem> orderItemList);


    /**
     * 通过用户id和订单号查询详情
     * @param userId
     * @param orderNo
     * @return
     */
    List<OrderItem> selectByUserIdOrderNo(@Param("userId") Integer userId,@Param("orderNo") String orderNo);

    /**
     * 管理员查询某一订单
     * @param orderNo
     * @return
     */
    List<OrderItem> selectByOrderNo(@Param("orderNo") String orderNo);
}