package com.gdut.graduation.dao;

import com.gdut.graduation.pojo.Order;
import org.apache.ibatis.annotations.Param;

import java.util.List;

public interface OrderMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table graduation_order
     *
     * @mbggenerated
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table graduation_order
     *
     * @mbggenerated
     */
    int insert(Order record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table graduation_order
     *
     * @mbggenerated
     */
    Order selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table graduation_order
     *
     * @mbggenerated
     */
    List<Order> selectAll();

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table graduation_order
     *
     * @mbggenerated
     */
    int updateByPrimaryKey(Order record);

    /**
     * 通过用户id和订单号查找订单
     * @param userId
     * @param orderNo
     * @return
     */
    Order selectByUserIdOrderNo(@Param("userId") Integer userId, @Param("orderNo") String orderNo);

    /**
     * 通过用户的id查找所有的订单
     * @param userId
     * @return
     */
    List<Order> selectByUserId(Integer userId);

    /**
     * 通过订单号查找订单，提供给管理员
     * @param orderNo
     * @return
     */
    Order selectByOrderNo(String orderNo);

}