package com.gdut.graduation.dao;

import com.gdut.graduation.pojo.Product;
import org.apache.ibatis.annotations.Param;

import java.util.List;

public interface ProductMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table graduation_product
     *
     * @mbggenerated
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table graduation_product
     *
     * @mbggenerated
     */
    int insert(Product record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table graduation_product
     *
     * @mbggenerated
     */
    Product selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table graduation_product
     *
     * @mbggenerated
     */
    List<Product> selectAll();

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table graduation_product
     *
     * @mbggenerated
     */
    int updateByPrimaryKey(Product record);

    /**
     * 查找某一状态的产品列表
     * @param status
     * @return
     */
    List<Product> selectByStatus(Integer status);

    /**
     * 通过产品的名字模糊查询列表和产品的id精确查找id
     */
    List<Product> selectByProductNameId(@Param("productName") String productName, @Param("id") Integer id);

    List<Product> selectByProductNameCategoryIds(@Param("productName") String productName, @Param("categoryIdList") List<Integer> categoryIdList);
}