package com.gdut.graduation.dao;

import com.gdut.graduation.pojo.Shipping;
import org.apache.ibatis.annotations.Param;

import java.util.List;

public interface ShippingMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table graduation_shipping
     *
     * @mbggenerated
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table graduation_shipping
     *
     * @mbggenerated
     */
    int insert(Shipping record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table graduation_shipping
     *
     * @mbggenerated
     */
    Shipping selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table graduation_shipping
     *
     * @mbggenerated
     */
    List<Shipping> selectAll();

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table graduation_shipping
     *
     * @mbggenerated
     */
    int updateByPrimaryKey(Shipping record);

    /**
     * 通过收获地址id和收获用户id，删除收获信息，防止越权问题的产生
     * @param shippingId 收获地址id
     * @param userId 用户id
     * @return
     */
    int deleteByShippingIdUserId(@Param("shippingId") Integer shippingId, @Param("userId") Integer userId);

    /**
     * 通过收获地址id和收获用户id，更新收获信息，防止越权问题的产生
     * @param shipping 收获地址id
     * @return
     */
    int updateByShippingIdUserId(Shipping shipping);

    /**
     * 通过收获地址id和收获用户id查找收获地址的信息
     * @param shippingId 收获地址id
     * @param userId 用户id
     * @return
     */
    Shipping selectByShippingIdUserId(@Param("shippingId") Integer shippingId, @Param("userId") Integer userId);

    /**
     * 通过用户id，查找该用户的所有的收获地址信息
     * @param userId 用户id
     * @return
     */
    List<Shipping> selectByUserId(@Param("userId") Integer userId);

}