package com.gdut.graduation.dao;

import com.gdut.graduation.pojo.User;
import org.apache.ibatis.annotations.Param;

import java.util.List;

public interface UserMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table graduation_user
     *
     * @mbggenerated
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table graduation_user
     *
     * @mbggenerated
     */
    int insert(User record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table graduation_user
     *
     * @mbggenerated
     */
    User selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table graduation_user
     *
     * @mbggenerated
     */
    List<User> selectAll();

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table graduation_user
     *
     * @mbggenerated
     */
    int updateByPrimaryKey(User record);

    int updateByPrimaryKeySelective(User record);

    /**
     * 通过用户名和密码获取用户的信息
     */
    User selectByUsernameAndPassword(@Param("username") String username, @Param("password") String password);

    /**
     * 通过用户名查找用户，判断用户是否注册
     */
    int selectByUsername(String username);

    /**
     * 校验邮件是否存在
     * @param email
     * @return
     */
    int checkEmail(String email);

    /**
     * 教养邮件是否存在
     * @param username
     * @return
     */
    int checkUsername(String username);

    /**
     * 校验密码，用户id和用户密码
     * @param password
     * @param userId
     * @return
     */
    int checkPassword(@Param("password") String password,@Param("userId") Integer userId);


}