server:
  port: 8088
spring:
  datasource:
    username: root
    password: skye
    url: jdbc:mysql://localhost:4306/graduation?useUnicode=true&characterEncoding=UTF-8&zeroDateTimeBehavior=convertToNull&allowMultiQueries=true&useSSL=false&serverTimezone=GMT%2B8
    driver-class-name: com.mysql.cj.jdbc.Driver
  jackson:
    default-property-inclusion: non_null
mybatis:
  mapper-locations: classpath:mappers/*.xml
#mapper接口查询的控制台显示
logging:
  level:
    com.gdut.graduation.dao : trace